# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # command: npm run start:dev
    container_name: project-management
    environment:
      DATABASE_URI: mongodb+srv://yuvaprasath:HhMwcDHFrftQOKZ7@cluster0.cxlprks.mongodb.net/api
    ports:
      - '3000:3000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    # restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: yuvaprasath
      MONGO_INITDB_ROOT_PASSWORD: HhMwcDHFrftQOKZ7
